"""Current tables and const

Revision ID: c1a41d2753f5
Revises: 1895d9898613
Create Date: 2026-04-23 21:40:45.796888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a41d2753f5'
down_revision: Union[str, Sequence[str], None] = '1895d9898613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hairdressers', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hairdressers', 'image_url')
    # ### end Alembic commands ###
