"""initial table

Revision ID: cba5c918b793
Revises: 
Create Date: 2026-04-21 23:48:57.626854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba5c918b793'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_salon_salon_name', 'salons', ['salon_name'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('verification_code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sms_verifications_phone_number_created_at', 'sms_verifications', ['phone_number', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('level_right', sa.Numeric(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hairdressers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hairdresser_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')", name='chk_status'),
    sa.CheckConstraint('ends_at > starts_at', name='chk_shifts_booking'),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdressers.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_hairdresser_id_starts_at', 'bookings', ['hairdresser_id', 'starts_at'], unique=False)
    op.create_index('ix_bookings_salon_id_starts_at', 'bookings', ['salon_id', 'starts_at'], unique=False)
    op.create_index('ix_bookings_username_starts_at', 'bookings', ['username', 'starts_at'], unique=False)
    op.create_table('hairdresser_salons',
    sa.Column('hairdresser_id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdressers.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('hairdresser_id', 'salon_id')
    )
    op.create_table('hairdresser_services',
    sa.Column('hairdresser_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdressers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('hairdresser_id', 'service_id')
    )
    op.create_table('hairdresser_work_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hairdresser_id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='chk_pattern_period'),
    sa.CheckConstraint('shift_end > shift_start', name='chk_pattern_time'),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name='chk_pattern_weekday'),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdressers.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hairdresser_work_patterns_hairdresser_id_weekday', 'hairdresser_work_patterns', ['hairdresser_id', 'weekday'], unique=False)
    op.create_index('ix_hairdresser_work_patterns_salon_id_weekday', 'hairdresser_work_patterns', ['salon_id', 'weekday'], unique=False)
    op.create_table('hairdresser_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hairdresser_id', sa.UUID(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.BigInteger(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source', sa.String(), server_default='pattern', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('pattern', 'manual', 'override')", name='chk_source'),
    sa.CheckConstraint('shift_end > shift_start', name='chk_schedule_time'),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdressers.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['hairdresser_work_patterns.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hairdresser_schedules_hairdresser_id_shift_start', 'hairdresser_schedules', ['hairdresser_id', 'shift_start'], unique=False)
    op.create_index('ix_hairdresser_schedules_hairdresser_id_work_date', 'hairdresser_schedules', ['hairdresser_id', 'work_date'], unique=False)
    op.create_index('ix_hairdresser_schedules_salon_id_work_date', 'hairdresser_schedules', ['salon_id', 'work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hairdresser_schedules_salon_id_work_date', table_name='hairdresser_schedules')
    op.drop_index('ix_hairdresser_schedules_hairdresser_id_work_date', table_name='hairdresser_schedules')
    op.drop_index('ix_hairdresser_schedules_hairdresser_id_shift_start', table_name='hairdresser_schedules')
    op.drop_table('hairdresser_schedules')
    op.drop_index('ix_hairdresser_work_patterns_salon_id_weekday', table_name='hairdresser_work_patterns')
    op.drop_index('ix_hairdresser_work_patterns_hairdresser_id_weekday', table_name='hairdresser_work_patterns')
    op.drop_table('hairdresser_work_patterns')
    op.drop_table('hairdresser_services')
    op.drop_table('hairdresser_salons')
    op.drop_index('ix_bookings_username_starts_at', table_name='bookings')
    op.drop_index('ix_bookings_salon_id_starts_at', table_name='bookings')
    op.drop_index('ix_bookings_hairdresser_id_starts_at', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('hairdressers')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_index('ix_sms_verifications_phone_number_created_at', table_name='sms_verifications')
    op.drop_table('sms_verifications')
    op.drop_table('services')
    op.drop_index('ix_salon_salon_name', table_name='salons')
    op.drop_table('salons')
    # ### end Alembic commands ###
