"""Update db

Revision ID: f848393f0ad4
Revises: c1a41d2753f5
Create Date: 2026-05-28 23:13:08.233085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f848393f0ad4'
down_revision: Union[str, Sequence[str], None] = 'c1a41d2753f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hairdressers', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hairdressers', 'description')
    # ### end Alembic commands ###
