// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorize = `-- name: Authorize :one
INSERT INTO users (username, full_name, phone_number) VALUES ($1, $2::varchar, $3)
ON CONFLICT (username) DO UPDATE SET last_login=now() WHERE username=excluded.username AND phone_number=excluded.phone_number
RETURNING username, full_name, phone_number, is_verified, created_at, updated_at, last_login
`

type AuthorizeParams struct {
	Username    string      `json:"username"`
	FullName    pgtype.Text `json:"full_name"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) Authorize(ctx context.Context, arg AuthorizeParams) (User, error) {
	row := q.db.QueryRow(ctx, authorize, arg.Username, arg.FullName, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const changePhoneNumber = `-- name: ChangePhoneNumber :one
UPDATE users SET phone_number=$1, updated_at=now() where username=$2 RETURNING username, full_name, phone_number, is_verified, created_at, updated_at, last_login
`

type ChangePhoneNumberParams struct {
	PhoneNumber string `json:"phone_number"`
	Username    string `json:"username"`
}

func (q *Queries) ChangePhoneNumber(ctx context.Context, arg ChangePhoneNumberParams) (User, error) {
	row := q.db.QueryRow(ctx, changePhoneNumber, arg.PhoneNumber, arg.Username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const verify = `-- name: Verify :exec
UPDATE users SET is_verified=true, updated_at=now() where username=$1
`

func (q *Queries) Verify(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, verify, username)
	return err
}
