// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePhoneNumber = `-- name: ChangePhoneNumber :one
UPDATE users SET phone_number = $1, updated_at=now() WHERE username=$2 RETURNING username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role
`

type ChangePhoneNumberParams struct {
	PhoneNumber string `json:"phone_number"`
	Username    string `json:"username"`
}

func (q *Queries) ChangePhoneNumber(ctx context.Context, arg ChangePhoneNumberParams) (User, error) {
	row := q.db.QueryRow(ctx, changePhoneNumber, arg.PhoneNumber, arg.Username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(username, email, phone_number)
VALUES ($1::varchar, $2::text, $3::varchar)
RETURNING username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role
`

type CreateUserParams struct {
	Username    pgtype.Text `json:"username"`
	Email       string      `json:"email"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email=$1) AS exists
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByPhoneNumber = `-- name: ExistsByPhoneNumber :one
SELECT EXISTS(SELECT 1 FROM users WHERE phone_number=$1) AS exists
`

func (q *Queries) ExistsByPhoneNumber(ctx context.Context, phoneNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByPhoneNumber, phoneNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByUsername = `-- name: ExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username=$1) AS exists
`

func (q *Queries) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role FROM users WHERE email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role FROM users WHERE phone_number=$1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role FROM users WHERE username=$1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login=now(), updated_at=now() WHERE username = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, username)
	return err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET is_verified=true, last_login=now(), updated_at=now() WHERE
    ($1::varchar is null or phone_number = $1::varchar)
    AND ($2::text is null or email = $2::text) RETURNING username, full_name, phone_number, is_verified, created_at, updated_at, last_login, uid, email, role
`

type VerifyUserParams struct {
	PhoneNumber pgtype.Text `json:"phone_number"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, arg.PhoneNumber, arg.Email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.PhoneNumber,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.Uid,
		&i.Email,
		&i.Role,
	)
	return i, err
}
