// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings(username, hairdresser_id, service_id, salon_id, starts_at, ends_at, description, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, hairdresser_id, service_id, salon_id, starts_at, ends_at, description, status, created_at, updated_at
`

type CreateBookingParams struct {
	Username      string             `json:"username"`
	HairdresserID uuid.UUID          `json:"hairdresser_id"`
	ServiceID     int32              `json:"service_id"`
	SalonID       int32              `json:"salon_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Description   pgtype.Text        `json:"description"`
	Status        string             `json:"status"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Username,
		arg.HairdresserID,
		arg.ServiceID,
		arg.SalonID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Description,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HairdresserID,
		&i.ServiceID,
		&i.SalonID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :many
SELECT id, username, hairdresser_id, service_id, salon_id, starts_at, ends_at, description, status, created_at, updated_at FROM bookings WHERE
                           ($1::varchar is null or username=$1::varchar)
                            AND ($2::bigint is null or id=$2::bigint)
                            AND ($3::uuid is null or hairdresser_id=$3::uuid)
                            AND ($4::integer is null or service_id=$4::integer)
                            AND ($5::integer is null or salon_id=$5::integer)
`

type GetBookingParams struct {
	Username      pgtype.Text `json:"username"`
	ID            pgtype.Int8 `json:"id"`
	HairdresserID pgtype.UUID `json:"hairdresser_id"`
	ServiceID     pgtype.Int4 `json:"service_id"`
	SalonID       pgtype.Int4 `json:"salon_id"`
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBooking,
		arg.Username,
		arg.ID,
		arg.HairdresserID,
		arg.ServiceID,
		arg.SalonID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HairdresserID,
			&i.ServiceID,
			&i.SalonID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
