// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID         uuid.UUID          `json:"id"`
	Username   string             `json:"username"`
	LevelRight float64            `json:"level_right"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	HairdresserID uuid.UUID          `json:"hairdresser_id"`
	ServiceID     int32              `json:"service_id"`
	SalonID       int32              `json:"salon_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Description   pgtype.Text        `json:"description"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Hairdresser struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Description pgtype.Text        `json:"description"`
}

type HairdresserSalon struct {
	HairdresserID uuid.UUID `json:"hairdresser_id"`
	SalonID       int32     `json:"salon_id"`
}

type HairdresserSchedule struct {
	ID            int64     `json:"id"`
	HairdresserID uuid.UUID `json:"hairdresser_id"`
	SalonID       int32     `json:"salon_id"`
	// NULL = разовая смена вне шаблона
	PatternID  pgtype.Int8        `json:"pattern_id"`
	WorkDate   pgtype.Date        `json:"work_date"`
	ShiftStart pgtype.Timestamptz `json:"shift_start"`
	ShiftEnd   pgtype.Timestamptz `json:"shift_end"`
	// false = отпуск/больничный/блок
	IsAvailable bool               `json:"is_available"`
	Source      string             `json:"source"`
	Comment     pgtype.Text        `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HairdresserService struct {
	HairdresserID uuid.UUID `json:"hairdresser_id"`
	ServiceID     int32     `json:"service_id"`
}

type HairdresserWorkPattern struct {
	ID            int64     `json:"id"`
	HairdresserID uuid.UUID `json:"hairdresser_id"`
	SalonID       int32     `json:"salon_id"`
	// ISO: 1=Пн ... 7=Вс
	Weekday       int16       `json:"weekday"`
	ShiftStart    pgtype.Time `json:"shift_start"`
	ShiftEnd      pgtype.Time `json:"shift_end"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
	// NULL = бессрочно
	EffectiveTo pgtype.Date        `json:"effective_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Salon struct {
	ID        int32              `json:"id"`
	SalonName string             `json:"salon_name"`
	Address   string             `json:"address"`
	Phone     string             `json:"phone"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID          int32           `json:"id"`
	ServiceName string          `json:"service_name"`
	Duration    pgtype.Interval `json:"duration"`
	Price       float64         `json:"price"`
	Description pgtype.Text     `json:"description"`
}

type SmsVerification struct {
	ID                   int64              `json:"id"`
	PhoneNumber          string             `json:"phone_number"`
	VerificationCodeHash string             `json:"verification_code_hash"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	IsUsed               bool               `json:"is_used"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	Username    string             `json:"username"`
	FullName    pgtype.Text        `json:"full_name"`
	PhoneNumber string             `json:"phone_number"`
	IsVerified  bool               `json:"is_verified"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLogin   pgtype.Timestamptz `json:"last_login"`
	Uid         uuid.UUID          `json:"uid"`
}
