// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	Authorize(ctx context.Context, arg AuthorizeParams) (User, error)
	ChangePhoneNumber(ctx context.Context, arg ChangePhoneNumberParams) (User, error)
	Verify(ctx context.Context, username string) error
}

var _ Querier = (*Queries)(nil)
