// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ChangePhoneNumber(ctx context.Context, arg ChangePhoneNumberParams) (User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ExistsByPhoneNumber(ctx context.Context, phoneNumber string) (bool, error)
	ExistsByUsername(ctx context.Context, username string) (bool, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateLastLogin(ctx context.Context, username string) error
	VerifyUser(ctx context.Context, username string) error
}

var _ Querier = (*Queries)(nil)
